services:
  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT:-3003}
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "${PORT:-3003}:${PORT:-3003}"
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4096m"
        reservations:
          cpus: "0.5"
          memory: "512m"
