export const configVar = () => ({
  ENABLE_EXPERIMENTAL_COREPACK: process.env.ENABLE_EXPERIMENTAL_COREPACK,
  PORT: Number(process.env.PORT) || 3000,
  LOGGER_LEVEL: process.env.LOGGER_LEVEL,
  MONGO_CONNECTION_STRING: process.env.MONGO_CONNECTION_STRING,
  SECRET: process.env.SECRET,
  SUPABASE_KEY: process.env.SUPABASE_KEY,
  SUPABASE_URL: process.env.SUPABASE_URL,
  FILES_DURATION: Number(process.env.FILES_DURATION) || 60,
  CDN_URL: process.env.CDN_URL,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_USERNAME: process.env.REDIS_USERNAME,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_DB: process.env.REDIS_DB,
  REDIS_PORT: process.env.REDIS_PORT,
  STRIPE_API_KEY: process.env.STRIPE_API_KEY,
});
