export enum Configuration {
  ENABLE_EXPERIMENTAL_COREPACK = "ENABLE_EXPERIMENTAL_COREPACK",
  LOGGER_LEVEL = "LOGGER_LEVEL",
  PORT = "PORT",
  MONGO_CONNECTION_STRING = "MONGO_CONNECTION_STRING",
  SECRET = "SECRET",
  SUPABASE_KEY = "SUPABASE_KEY",
  SUPABASE_URL = "SUPABASE_URL",
  FILES_DURATION = "FILES_DURATION",
}
