export enum Configuration {
  LOGGER_LEVEL = "LOGGER_LEVEL",
  PORT = "PORT",
  MONGO_CONNECTION_STRING = "MONGO_CONNECTION_STRING",
  SECRET = "SECRET",
  CDN_URL = "CDN_URL",
  REDIS_HOST = "REDIS_HOST",
  REDIS_USERNAME = "REDIS_USERNAME",
  REDIS_PASSWORD = "REDIS_PASSWORD",
  REDIS_DB = "REDIS_DB",
  REDIS_PORT = "REDIS_PORT",
  STRIPE_API_KEY = "STRIPE_API_KEY",

  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
  BASE_API_URL = "BASE_API_URL",
  DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID",
  DISCORD_CLIENT_SECRET = "DISCORD_CLIENT_SECRET",
  POSTHOG_API_KEY = "POSTHOG_API_KEY",
  POSTHOG_PROJECT_URL = "POSTHOG_PROJECT_URL",

}
