export enum Configuration {
  LOGGER_LEVEL = "LOGGER_LEVEL",
  PORT = "PORT",
  MONGO_CONNECTION_STRING = "MONGO_CONNECTION_STRING",
  SECRET = "SECRET",
  CDN_URL = "CDN_URL",
  REDIS_HOST = "REDIS_HOST",
  REDIS_USERNAME = "REDIS_USERNAME",
  REDIS_PASSWORD = "REDIS_PASSWORD",
  REDIS_DB = "REDIS_DB",
  REDIS_PORT = "REDIS_PORT",
  STRIPE_API_KEY = "STRIPE_API_KEY",

  GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET",
}
